# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: AdvancedSecurity-Codeql-Init@1
  inputs:
    languages: 'csharp'
    querysuite: 'code-scanning'
    buildtype: 'None'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# - task: AdvancedSecurity-Codeql-Analyze@1
#   inputs:
#     WaitForProcessing: true

- task: AdvancedSecurity-Publish@1
  inputs:
    EnableRecursiveScanning: true
    WaitForProcessing: true

- task: Docker@2
  inputs:
    containerRegistry: 'MVCDocker'
    repository: 'ambarajv/ASPDotNetMVC'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/ASPDotNetMVC/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)/ASPDotNetMVC'