# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

#----------------------Build Stage------------------------------#

#steps:
stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
#AdvanceSecurity Initiate
    - task: AdvancedSecurity-Codeql-Init@1
      inputs:
        languages: 'csharp'
        querysuite: 'code-scanning'
        buildtype: 'None'

#SonarCloud Prepare
    - task: SonarCloudPrepare@4
      inputs:
        SonarQube: 'SonarCloudMVC'
        organization: 'devops-ambara'
        scannerMode: 'dotnet'
        projectKey: 'devops-Ambara_ASPDotNetMVC'
        projectName: 'ASPDotNetMVC'

#.NetCore Restore
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        feedsToUse: 'select'
        vstsFeed: 'd219ec30-aea4-4942-835c-82081597e8ee'


#.NetCore Build
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'

#Artifacts
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

#Publish Build Artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

#Build
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'

#AdvanceSecurity Analysis

# - task: AdvancedSecurity-Codeql-Analyze@1
#   inputs:
#     WaitForProcessing: true

#----------------------Test Stage------------------------------#

- stage: Test
  dependsOn: Build
  jobs:
  - job: TestJob
    steps:

#.NetCore Test
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        arguments: '--configuration Release --collect "Code coverage"'

#Code Coverage
    - task: PublishCodeCoverageResults@2
      inputs:
        summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

#----------------------Analyze Stage------------------------------#

- stage: Analyze
  dependsOn: Test
  jobs:
  - job: AnalyzeJob
    steps:

#AdvanceSecurity Publish
    - task: AdvancedSecurity-Publish@1
      inputs:
        EnableRecursiveScanning: true
        WaitForProcessing: true

#SonarCloud Analysis
    - task: SonarCloudAnalyze@4
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

#SonarCloud Publish
    - task: SonarCloudPublish@4
      inputs:
        pollingTimeoutSec: '300'

#----------------------Docker Stage------------------------------#

- stage: Docker
  dependsOn: Analyze
  jobs:
  - job: DockerJob
    steps:

#Docker Configuration
    #Docker Build
    - task: Docker@2
      inputs:
        containerRegistry: 'MVCDocker'
        repository: 'ambarajv/ASPDotNetMVC'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/ASPDotNetMVC/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/ASPDotNetMVC'
        tags: |
          $(Build.BuildId)
          latest
    #Docker Push
    - task: Docker@2
      inputs:
        containerRegistry: 'MVCDocker'
        repository: 'ambarajv/ASPDotNetMVC'
        command: 'push'
        tags: |
          $(Build.BuildId)
          latest

#----------------------Deploy Stage------------------------------#

# - stage: Deploy
#   dependsOn: Docker
#   jobs:
#   - job: DeployJob
#     steps:

#     - task: AzureWebAppContainer@1
#       inputs:
#         azureSubscription: 'Your-Service-Connection'
#         appName: 'ASPDotNetMVC'
#         containers: 'ambarajv/ASPDotNetMVC:latest'